New Game Setting in the Launcher - Enable CPU Compatibility Mode.
ProjectCeleste/Celeste.Launcher pull request #101
Opened 2024-03-21 02:38 UTC by CWO333

New setting added under Settings -> Game Settings in the Launcher. CPU Compatibility Mode restricts the game to the first 4 CPU cores (Affinity 0xF) and sets the Process Priority to High. This fixes some C++ Runtime crashes as well as some other random glitches.

By default the setting is disabled.

Need translations for the following strings:

(Dialogs)
EnableCPUCompatibilityMode - "CPU Compatibility Mode is now Enabled."
DisableCPUCompatibilityMode - "CPU Compatibility Mode is now Disabled."

(Menu text)
OverviewEnableCPUCompatibilityMode - "Enable CPU Compatibility Mode"

2024-03-22 18:23 UTC, martinmine requested changes
Thanks a lot for the PR, I really appreciate it! Really cool to see that it is not that much work to get this up and running. Please see my comments and feel free to reach out on Discord if you have any questions or anything.

2024-03-22 18:23 UTC, martinmine commented on Celeste_Launcher_Gui/Pages/OverviewPage.xaml.cs
> +
This line is unused and can be removed

2024-03-22 18:23 UTC, martinmine commented on Celeste_Launcher_Gui/Pages/OverviewPage.xaml.cs
> +            else
It would be great if you could add { } around the else so we are consequent with the styling

2024-03-22 18:23 UTC, martinmine commented on Celeste_Launcher_Gui/Services/GameService.cs
> +                Process SProcess = Process.Start(new ProcessStartInfo(spartanPath, arg) { WorkingDirectory = gamePath });
```suggestion
                var gameProcess = Process.Start(new ProcessStartInfo(spartanPath, arg) { WorkingDirectory = gamePath });
```
We normally use `var` instead of explicitly refering to the type, and variable names usually start with lowercase

2024-03-22 18:23 UTC, martinmine commented on Celeste_Launcher_Gui/Properties/Resources.resx
> +    <value>Enable CPU Compatibility Mode</value>
From a non-technical perspective I would understand that this is easier for us to communicate to players that want to use this feature. However, from a technical perspective "CPU compatibility" could in some cases also be misleading as I would think it could be some emulation that takes place (like x86 -> ARM or w.e.). One suggestion would be to call it "Enforce processor affinity", but this could again be too technical for people to understand without the given context. Do you have any thoughts?

2024-03-22 18:23 UTC, martinmine commented on Celeste_Launcher_Gui/Services/GameService.cs
> +
Unused space that can be removed
```suggestion
```

2024-03-22 20:35 UTC, CWO333 commented on Celeste_Launcher_Gui/Properties/Resources.resx
> +    <value>Enable CPU Compatibility Mode</value>
Maybe "Limited Processor Mode" or "Limit CPU Cores"?

2024-03-23 18:55 UTC, CWO333 commented on Celeste_Launcher_Gui/Properties/Resources.resx
> +    <value>Enable CPU Compatibility Mode</value>
Changed to Limit CPU Cores

2024-03-27 19:30 UTC, merged